version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - redis
    networks:
      - app-network

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  zarr_db:
    build:
      context: ./zarr
      dockerfile: Dockerfile
    container_name: zarr_db
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
